### ISSUE TITLE
`input` property names not highlighted 

### ISSUE THREAD

**Issue by shellscape** [11bit/zed-extension-graphql#1]
👋  first off, thanks for putting this extension together!

Wanted to drop by to let you know that `input` property names aren't being highlighted. That might be an upstream issue in the grammar used, but at least there's some tracking around it.

<img width="208" alt="Screenshot 2024-03-11 at 10 18 37 PM" src="https://github.com/11bit/zed-extension-graphql/assets/76371/6d2f8286-b863-47f6-be99-8e057cafe3ae">

**Comment by 11bit** [comment]
@shellscape Thanks for noticing! Should be fixed in v0.0.2 after merge https://github.com/zed-industries/extensions/pull/329
