### ISSUE TITLE
Support for .graphqls

### ISSUE THREAD

**Issue by whatjackhasmade** [11bit/zed-extension-graphql#5]
Love the extension, could we extend it to support `.graphqls` files too?

These are used to define schema files, and separate the concerns between schema definitions and query/mutation files.

I tried to create the PR myself but it looks like that isn't supported.

**Comment by 11bit** [comment]
Hey @whatjackhasmade, I've never heard of .graphqls files. Is it the same syntax but just for schemas? If yes, you can even do to with [File Types](https://zed.dev/docs/configuring-zed#file-types) config
